import { ensureServerOnly } from "./guard";
import type {
  User,
  Profile,
  Experience,
  Education,
  Skill,
  Project,
  Certification,
  Language,
  JobPreference,
  Resume,
  Job,
  JobMatch,
  Application,
  Generation,
} from "@/types/database";

ensureServerOnly("mock-db");

export const mockUser: User = {
  id: "usr_mock_01",
  email: "alex.morgan@example.com",
  name: "Alex Morgan",
  role: "user",
  subscriptionTier: "professional",
  subscriptionStatus: "active",
  createdAt: "2026-01-15T08:00:00Z",
  updatedAt: "2026-03-01T12:00:00Z",
};

export const mockProfile: Profile = {
  id: "prof_mock_01",
  userId: "usr_mock_01",
  fullName: "Alex Morgan",
  professionalHeadline: "Senior Full-Stack & Distributed Systems Engineer",
  email: "alex.morgan@example.com",
  phone: "+1 (555) 234-8901",
  location: "Seattle, WA (Open to Remote)",
  linkedInUrl: "https://linkedin.com/in/alex-morgan-dev",
  githubUrl: "https://github.com/alexmorgan-dev",
  portfolioUrl: "https://alexmorgan.codes",
  currentJobTitle: "Senior Software Engineer",
  yearsOfExperience: 6,
  industry: "Enterprise SaaS & Cloud Infrastructure",
  careerLevel: "senior",
  employmentStatus: "open_to_work",
  completionPercentage: 88,
  createdAt: "2026-01-15T08:30:00Z",
  updatedAt: "2026-03-01T14:20:00Z",
};

export const mockExperiences: Experience[] = [
  {
    id: "exp_01",
    profileId: "prof_mock_01",
    company: "CloudScale Technologies",
    jobTitle: "Senior Software Engineer",
    location: "Seattle, WA",
    isRemote: true,
    employmentType: "full_time",
    startDate: "2023-04",
    isCurrent: true,
    responsibilities: [
      "Architected and deployed event-driven microservices processing 45M+ daily requests using Go, Node.js, and Apache Kafka.",
      "Led high-throughput database sharding and performance tuning on PostgreSQL reducing p99 latency by 38%.",
      "Mentored 4 junior and mid-level engineers across system design, testing best practices, and CI/CD pipelines.",
    ],
    achievements: [
      "Reduced cloud compute overhead by $120k annually through container right-sizing and caching optimization.",
      "Designed real-time telemetry pipeline delivering sub-second anomaly detection across 12 distributed clusters.",
    ],
    technologiesUsed: ["Go", "TypeScript", "Node.js", "PostgreSQL", "Kafka", "Docker", "Kubernetes", "AWS"],
    createdAt: "2026-01-15T09:00:00Z",
    updatedAt: "2026-02-10T11:00:00Z",
  },
  {
    id: "exp_02",
    profileId: "prof_mock_01",
    company: "Vanguard Digital Labs",
    jobTitle: "Full-Stack Engineer",
    location: "San Francisco, CA",
    isRemote: false,
    employmentType: "full_time",
    startDate: "2020-08",
    endDate: "2023-03",
    isCurrent: false,
    responsibilities: [
      "Engineered customer-facing analytics dashboards using Next.js, React, TypeScript, and Tailwind CSS.",
      "Constructed REST and GraphQL endpoints backed by Node.js and Redis caching layers.",
      "Collaborated closely with product designers and security auditors to achieve SOC2 compliance.",
    ],
    achievements: [
      "Improved Lighthouse performance scores from 54 to 98 through dynamic bundle splitting and asset caching.",
      "Spearheaded redesign of data query engine accelerating client report generation by 4x.",
    ],
    technologiesUsed: ["Next.js", "React", "TypeScript", "Tailwind CSS", "GraphQL", "Redis", "Jest"],
    createdAt: "2026-01-15T09:15:00Z",
    updatedAt: "2026-01-15T09:15:00Z",
  },
];

export const mockEducation: Education[] = [
  {
    id: "edu_01",
    profileId: "prof_mock_01",
    institution: "University of Washington",
    degree: "Bachelor of Science",
    fieldOfStudy: "Computer Science & Engineering",
    startDate: "2016-09",
    endDate: "2020-06",
    gpa: "3.85 / 4.0",
    honors: ["Dean's List (All Quarters)", "Magna Cum Laude"],
    createdAt: "2026-01-15T09:30:00Z",
    updatedAt: "2026-01-15T09:30:00Z",
  },
];

export const mockSkills: Skill[] = [
  {
    id: "skl_01",
    profileId: "prof_mock_01",
    name: "TypeScript",
    category: "programming_languages",
    proficiencyLevel: "professional_experience",
    yearsOfExperience: 6,
    verifiedViaInterview: true,
    evidenceNotes: "Primary language for 4+ production enterprise applications; strict typing advocate.",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-02-12T14:00:00Z",
  },
  {
    id: "skl_02",
    profileId: "prof_mock_01",
    name: "Next.js",
    category: "frameworks",
    proficiencyLevel: "professional_experience",
    yearsOfExperience: 5,
    verifiedViaInterview: true,
    evidenceNotes: "Built SSR/SSG apps using App Router, Server Actions, Route Handlers, and Edge runtime.",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-02-12T14:00:00Z",
  },
  {
    id: "skl_03",
    profileId: "prof_mock_01",
    name: "React",
    category: "libraries",
    proficiencyLevel: "professional_experience",
    yearsOfExperience: 6,
    verifiedViaInterview: true,
    evidenceNotes: "Deep expertise in hooks, state modeling, concurrent rendering, and performance profiling.",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-02-12T14:00:00Z",
  },
  {
    id: "skl_04",
    profileId: "prof_mock_01",
    name: "PostgreSQL",
    category: "databases",
    proficiencyLevel: "professional_experience",
    yearsOfExperience: 5,
    verifiedViaInterview: true,
    evidenceNotes: "Schema design, index strategy (B-Tree, GIN), connection pooling, and replication tuning.",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-02-12T14:00:00Z",
  },
  {
    id: "skl_05",
    profileId: "prof_mock_01",
    name: "Go (Golang)",
    category: "programming_languages",
    proficiencyLevel: "professional_experience",
    yearsOfExperience: 3,
    verifiedViaInterview: true,
    evidenceNotes: "Built concurrent microservices, channel synchronization, and gRPC services.",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-02-12T14:00:00Z",
  },
  {
    id: "skl_06",
    profileId: "prof_mock_01",
    name: "Kubernetes & Docker",
    category: "devops",
    proficiencyLevel: "professional_experience",
    yearsOfExperience: 4,
    verifiedViaInterview: true,
    evidenceNotes: "Helm charts, pod disruption budgets, horizontal pod autoscaling, ingress configuration.",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-02-12T14:00:00Z",
  },
  {
    id: "skl_07",
    profileId: "prof_mock_01",
    name: "Apache Kafka",
    category: "tools",
    proficiencyLevel: "project_experience",
    yearsOfExperience: 2,
    verifiedViaInterview: false,
    evidenceNotes: "Used for distributed event streams, consumer groups, and partition balancing.",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-02-12T14:00:00Z",
  },
  {
    id: "skl_08",
    profileId: "prof_mock_01",
    name: "Python (AI/ML Tooling)",
    category: "programming_languages",
    proficiencyLevel: "has_used",
    yearsOfExperience: 2,
    verifiedViaInterview: false,
    evidenceNotes: "Basic scripting, LangChain integration experiments, data extraction scripts.",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-02-12T14:00:00Z",
  },
  {
    id: "skl_09",
    profileId: "prof_mock_01",
    name: "Rust",
    category: "programming_languages",
    proficiencyLevel: "beginner_familiarity",
    yearsOfExperience: 1,
    verifiedViaInterview: false,
    evidenceNotes: "Completed Rust Book and personal CLI utilities; no production deployment yet.",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-02-12T14:00:00Z",
  },
];

export const mockProjects: Project[] = [
  {
    id: "prj_01",
    profileId: "prof_mock_01",
    name: "StreamQuery Engine",
    description: "Open-source lightweight stream processor for filtering and aggregating high-volume WebSocket telemetry.",
    role: "Sole Author / Maintainer",
    technologies: ["Go", "WebSockets", "Redis", "Prometheus"],
    responsibilities: [
      "Engineered lock-free ring buffer yielding 1.2M events/sec throughput on modest commodity instances.",
      "Authored extensive documentation and benchmark suites.",
    ],
    achievements: ["Gathered 800+ GitHub stars and adopted by 3 fintech startups in production."],
    githubUrl: "https://github.com/alexmorgan-dev/streamquery",
    createdAt: "2026-01-15T10:30:00Z",
    updatedAt: "2026-02-01T15:00:00Z",
  },
];

export const mockCertifications: Certification[] = [
  {
    id: "cert_01",
    profileId: "prof_mock_01",
    name: "AWS Certified Solutions Architect – Associate",
    issuer: "Amazon Web Services",
    issueDate: "2024-05",
    expiryDate: "2027-05",
    credentialUrl: "https://aws.amazon.com/verification",
    credentialId: "AWS-PSA-982173",
    createdAt: "2026-01-15T10:45:00Z",
    updatedAt: "2026-01-15T10:45:00Z",
  },
];

export const mockLanguages: Language[] = [
  { id: "lang_01", profileId: "prof_mock_01", name: "English", proficiency: "native_bilingual" },
  { id: "lang_02", profileId: "prof_mock_01", name: "Spanish", proficiency: "professional_working" },
];

export const mockJobPreferences: JobPreference = {
  id: "pref_01",
  profileId: "prof_mock_01",
  desiredJobTitles: ["Staff Software Engineer", "Senior Full-Stack Engineer", "Senior Backend Engineer"],
  desiredIndustries: ["Cloud Infrastructure", "Enterprise SaaS", "Developer Tools", "FinTech"],
  targetLocations: ["Seattle, WA", "Remote (US)", "San Francisco, CA"],
  workplacePreference: "remote",
  minimumExperienceYears: 5,
  maximumCommuteMinutes: 30,
  employmentTypes: ["full_time"],
  minimumSalary: 175000,
  targetSalary: 215000,
  preferredTechnologies: ["TypeScript", "Next.js", "Go", "PostgreSQL", "AWS", "Kubernetes"],
  openToRelocation: false,
  createdAt: "2026-01-15T11:00:00Z",
  updatedAt: "2026-02-20T10:00:00Z",
};

export const mockResumes: Resume[] = [
  {
    id: "res_01",
    userId: "usr_mock_01",
    title: "Senior Full-Stack Engineer - Standard 2026",
    fileName: "Alex_Morgan_Senior_FullStack_Resume_2026.pdf",
    fileSize: 184320,
    fileType: "pdf",
    fileUrl: "/mock/resumes/Alex_Morgan_Senior_FullStack_Resume_2026.pdf",
    isPrimary: true,
    status: "active",
    parseStatus: "completed",
    analyzedAt: "2026-03-01T14:30:00Z",
    atsScore: 92,
    createdAt: "2026-02-01T09:00:00Z",
    updatedAt: "2026-03-01T14:30:00Z",
  },
  {
    id: "res_02",
    userId: "usr_mock_01",
    title: "Backend & Systems Infrastructure Specialist",
    fileName: "Alex_Morgan_Backend_Infrastructure_2026.docx",
    fileSize: 225280,
    fileType: "docx",
    fileUrl: "/mock/resumes/Alex_Morgan_Backend_Infrastructure_2026.docx",
    isPrimary: false,
    status: "active",
    parseStatus: "completed",
    analyzedAt: "2026-02-20T16:00:00Z",
    atsScore: 86,
    createdAt: "2026-02-18T10:00:00Z",
    updatedAt: "2026-02-20T16:00:00Z",
  },
];

export const mockJobs: Job[] = [
  {
    id: "job_01",
    title: "Senior Full-Stack Engineer (Core Platform)",
    company: "Stripe",
    location: "Seattle, WA (Remote US)",
    workplaceType: "remote",
    employmentType: "full_time",
    seniority: "senior",
    experienceYearsRequired: 5,
    salaryMin: 185000,
    salaryMax: 235000,
    salaryCurrency: "USD",
    description:
      "We are seeking a Senior Full-Stack Engineer to lead the architecture of our developer billing platform. You will build highly available web interfaces with Next.js/React and scale robust transaction services in Go and PostgreSQL handling millions of events daily.",
    requiredSkills: ["TypeScript", "React", "Next.js", "PostgreSQL", "Distributed Systems"],
    preferredSkills: ["Go", "Kafka", "AWS", "Stripe API"],
    responsibilities: [
      "Own end-to-end architecture from web UI to mission-critical backend transactional databases.",
      "Improve system reliability, latency, and observability across globally distributed payment services.",
      "Collaborate with product managers and developer experience engineers to ship frictionless billing tools.",
    ],
    educationRequirement: "B.S. in Computer Science or equivalent practical experience",
    sourceUrl: "https://stripe.com/jobs/senior-fullstack-core",
    postedAt: "2026-03-05T10:00:00Z",
    createdAt: "2026-03-05T10:00:00Z",
  },
  {
    id: "job_02",
    title: "Staff Distributed Systems Engineer",
    company: "Datadog",
    location: "New York, NY (Hybrid or Remote)",
    workplaceType: "hybrid",
    employmentType: "full_time",
    seniority: "lead",
    experienceYearsRequired: 7,
    salaryMin: 210000,
    salaryMax: 260000,
    salaryCurrency: "USD",
    description:
      "Datadog is looking for a Staff Engineer to build next-generation ingestion pipelines. You will design ultra-low-latency distributed stream processing clusters handling petabytes of telemetry per minute.",
    requiredSkills: ["Go", "Kubernetes", "Kafka", "Distributed Systems", "Linux Internals"],
    preferredSkills: ["Rust", "eBPF", "PostgreSQL"],
    responsibilities: [
      "Drive architectural decisions for multi-region ingestion brokers.",
      "Mentor senior engineers across system resilience and performance benchmarking.",
      "Collaborate on telemetry protocols with open-source communities.",
    ],
    educationRequirement: "Bachelor's or Master's degree in Computer Science",
    sourceUrl: "https://datadoghq.com/careers/staff-systems",
    postedAt: "2026-03-04T14:30:00Z",
    createdAt: "2026-03-04T14:30:00Z",
  },
  {
    id: "job_03",
    title: "Lead Frontend Engineer (Next.js / Design Systems)",
    company: "Vercel",
    location: "Remote (Global)",
    workplaceType: "remote",
    employmentType: "full_time",
    seniority: "lead",
    experienceYearsRequired: 6,
    salaryMin: 195000,
    salaryMax: 245000,
    salaryCurrency: "USD",
    description:
      "Join Vercel to craft the developer dashboard and component systems powering millions of global creators. You should be deeply versed in Next.js App Router, web accessibility (a11y), Tailwind CSS, and edge caching strategies.",
    requiredSkills: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Web Performance", "Accessibility"],
    preferredSkills: ["Node.js", "GraphQL", "Micro-frontend architecture"],
    responsibilities: [
      "Architect and scale Vercel's flagship web console.",
      "Partner with DX teams to build accessible, lightning-fast UI component primitives.",
      "Contribute to open-source Next.js examples and developer documentation.",
    ],
    educationRequirement: "Demonstrated portfolio of high-impact web applications",
    sourceUrl: "https://vercel.com/careers/lead-frontend",
    postedAt: "2026-03-02T11:00:00Z",
    createdAt: "2026-03-02T11:00:00Z",
  },
  {
    id: "job_04",
    title: "Senior Cloud Infrastructure Engineer",
    company: "Snowflake",
    location: "Bellevue, WA",
    workplaceType: "on_site",
    employmentType: "full_time",
    seniority: "senior",
    experienceYearsRequired: 5,
    salaryMin: 180000,
    salaryMax: 225000,
    salaryCurrency: "USD",
    description:
      "Build high-security multi-cloud foundations across AWS, Azure, and GCP for Snowflake's petabyte data cloud. Automate infrastructure as code with Terraform, Helm, and Go-based operators.",
    requiredSkills: ["AWS", "Kubernetes", "Docker", "Go", "Terraform"],
    preferredSkills: ["PostgreSQL", "Python", "Security Compliance"],
    responsibilities: [
      "Manage large-scale Kubernetes infrastructure across multiple cloud providers.",
      "Implement zero-trust security controls and audit automation.",
    ],
    educationRequirement: "B.S. in Computer Science or relevant technical field",
    sourceUrl: "https://snowflake.com/careers/cloud-infra",
    postedAt: "2026-03-01T08:00:00Z",
    createdAt: "2026-03-01T08:00:00Z",
  },
];

export const mockJobMatches: JobMatch[] = [
  {
    id: "match_01",
    userId: "usr_mock_01",
    jobId: "job_01",
    matchScore: 94,
    overallScore: 94,
    skillsMatchScore: 96,
    experienceMatchScore: 95,
    seniorityMatchScore: 90,
    matchingSkills: ["TypeScript", "React", "Next.js", "PostgreSQL", "Go", "Kafka", "AWS"],
    missingSkills: ["Stripe API (prior commercial integration)"],
    potentialConcerns: ["None detected; experience matches team stack closely."],
    recommendedAction: "Apply immediately with tailored resume emphasizing high-throughput Kafka & Next.js metrics.",
    isSaved: true,
    createdAt: "2026-03-05T10:15:00Z",
    updatedAt: "2026-03-05T10:15:00Z",
  },
  {
    id: "match_02",
    userId: "usr_mock_01",
    jobId: "job_02",
    matchScore: 82,
    overallScore: 82,
    skillsMatchScore: 80,
    experienceMatchScore: 85,
    seniorityMatchScore: 80,
    matchingSkills: ["Go", "Kubernetes", "Kafka", "Distributed Systems", "PostgreSQL"],
    missingSkills: ["eBPF", "Rust (Production)"],
    potentialConcerns: ["Role requests 7+ years of experience; your profile has 6 years."],
    recommendedAction: "Highlight StreamQuery open-source throughput benchmarks and Go concurrency depth.",
    isSaved: false,
    createdAt: "2026-03-04T15:00:00Z",
    updatedAt: "2026-03-04T15:00:00Z",
  },
  {
    id: "match_03",
    userId: "usr_mock_01",
    jobId: "job_03",
    matchScore: 96,
    overallScore: 96,
    skillsMatchScore: 98,
    experienceMatchScore: 95,
    seniorityMatchScore: 94,
    matchingSkills: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Web Performance"],
    missingSkills: ["Micro-frontend architecture"],
    potentialConcerns: ["Lead title requires cross-team design review track record."],
    recommendedAction: "Generate a tailored cover letter showcasing Lighthouse 98 optimization case study.",
    isSaved: true,
    createdAt: "2026-03-02T12:00:00Z",
    updatedAt: "2026-03-02T12:00:00Z",
  },
  {
    id: "match_04",
    userId: "usr_mock_01",
    jobId: "job_04",
    matchScore: 78,
    overallScore: 78,
    skillsMatchScore: 82,
    experienceMatchScore: 80,
    seniorityMatchScore: 85,
    matchingSkills: ["AWS", "Kubernetes", "Docker", "Go", "PostgreSQL"],
    missingSkills: ["Terraform", "Multi-Cloud Azure/GCP"],
    potentialConcerns: ["On-site in Bellevue vs. your stated remote preference."],
    recommendedAction: "Verify workplace flexibility before submitting formal application.",
    isSaved: false,
    createdAt: "2026-03-01T09:00:00Z",
    updatedAt: "2026-03-01T09:00:00Z",
  },
];

export const mockApplications: Application[] = [
  {
    id: "app_01",
    userId: "usr_mock_01",
    jobId: "job_01",
    jobTitle: "Senior Full-Stack Engineer (Core Platform)",
    company: "Stripe",
    location: "Seattle, WA (Remote US)",
    status: "interview",
    appliedDate: "2026-02-28",
    salaryOffered: undefined,
    notes: "Completed initial recruiter phone screen on March 3rd. Technical architecture round scheduled for next Thursday.",
    recruiter: {
      id: "rec_01",
      name: "Sarah Jenkins",
      company: "Stripe",
      title: "Senior Technical Recruiter",
      email: "sjenkins@stripe.com",
      linkedInUrl: "https://linkedin.com/in/sarah-jenkins-recruiter",
      isPublicInfo: true,
    },
    nextAction: "Review distributed transaction isolation levels & practice system design",
    nextActionDueDate: "2026-03-12",
    tailoredResumeId: "res_01",
    createdAt: "2026-02-28T14:00:00Z",
    updatedAt: "2026-03-03T16:45:00Z",
  },
  {
    id: "app_02",
    userId: "usr_mock_01",
    jobId: "job_03",
    jobTitle: "Lead Frontend Engineer (Next.js / Design Systems)",
    company: "Vercel",
    location: "Remote",
    status: "recruiter_contacted",
    appliedDate: "2026-03-02",
    notes: "Sent tailored cold outreach via email to Design Systems hiring manager. Awaiting response.",
    recruiter: {
      id: "rec_02",
      name: "Marcus Vance",
      company: "Vercel",
      title: "Engineering Manager - Design Infrastructure",
      email: "mvance@vercel.com",
      linkedInUrl: "https://linkedin.com/in/marcus-vance-dev",
      isPublicInfo: true,
    },
    nextAction: "Follow up via LinkedIn message if no reply by Monday",
    nextActionDueDate: "2026-03-09",
    tailoredResumeId: "res_01",
    createdAt: "2026-03-02T12:30:00Z",
    updatedAt: "2026-03-02T12:30:00Z",
  },
  {
    id: "app_03",
    userId: "usr_mock_01",
    jobTitle: "Principal Cloud Engineer",
    company: "Amazon Web Services",
    location: "Seattle, WA",
    status: "saved",
    notes: "Saved from internal referral recommendation. Need to prepare AWS Solutions Architect highlight.",
    nextAction: "Tailor resume using HireBoost AI Studio",
    nextActionDueDate: "2026-03-10",
    createdAt: "2026-03-04T09:00:00Z",
    updatedAt: "2026-03-04T09:00:00Z",
  },
  {
    id: "app_04",
    userId: "usr_mock_01",
    jobTitle: "Senior Software Engineer - Infrastructure",
    company: "Atlassian",
    location: "Remote",
    status: "applied",
    appliedDate: "2026-02-24",
    notes: "Submitted tailored application through company portal.",
    nextAction: "Check portal status",
    nextActionDueDate: "2026-03-10",
    createdAt: "2026-02-24T10:00:00Z",
    updatedAt: "2026-02-24T10:00:00Z",
  },
  {
    id: "app_05",
    userId: "usr_mock_01",
    jobTitle: "Staff Software Engineer",
    company: "Meta",
    location: "Bellevue, WA",
    status: "offer",
    appliedDate: "2026-01-20",
    salaryOffered: 235000,
    notes: "Offer received for Infrastructure Org. Reviewing equity vesting schedule and compensation breakdown.",
    nextAction: "Schedule compensation negotiation call",
    nextActionDueDate: "2026-03-11",
    createdAt: "2026-01-20T08:00:00Z",
    updatedAt: "2026-03-04T18:00:00Z",
  },
  {
    id: "app_06",
    userId: "usr_mock_01",
    jobTitle: "Senior Backend Developer",
    company: "Fintech Startup X",
    location: "San Francisco, CA",
    status: "rejected",
    appliedDate: "2026-02-05",
    notes: "Position closed internally due to headcount freeze.",
    createdAt: "2026-02-05T11:00:00Z",
    updatedAt: "2026-02-18T14:00:00Z",
  },
];

export const mockGenerations: Generation[] = [
  {
    id: "gen_01",
    userId: "usr_mock_01",
    type: "tailored_resume",
    jobId: "job_01",
    jobTitle: "Senior Full-Stack Engineer (Core Platform)",
    company: "Stripe",
    status: "completed",
    inputs: {
      tone: "professional",
      targetKeywords: ["PostgreSQL sharding", "Kafka", "High-throughput APIs"],
    },
    outputContent: `# Alex Morgan
Seattle, WA | alex.morgan@example.com | (555) 234-8901 | linkedin.com/in/alex-morgan-dev

## Professional Summary
Results-driven Senior Software Engineer with 6+ years specializing in distributed systems, high-concurrency microservices, and modern Next.js/React architectures. Proven track record architecting event-driven pipelines scaling to 45M+ daily requests with 99.99% uptime.

## Core Technical Skills
- **Languages:** TypeScript, Go (Golang), JavaScript, SQL
- **Frameworks & Libraries:** Next.js (App Router), React, Node.js, Express, Tailwind CSS
- **Data & Streaming:** PostgreSQL (Optimization, Sharding), Redis, Apache Kafka
- **Cloud & DevOps:** AWS, Docker, Kubernetes, CI/CD Pipelines

## Professional Experience
### CloudScale Technologies — Senior Software Engineer
*April 2023 – Present | Seattle, WA (Remote)*
- Architected and deployed Go & Node.js microservices processing 45M+ daily requests with Apache Kafka.
- Reduced p99 database latency by 38% across PostgreSQL clusters through targeted query indexing and connection tuning.
- Saved $120k annually in cloud compute expenses through container optimization and Redis caching layers.`,
    createdAt: "2026-03-05T11:00:00Z",
    updatedAt: "2026-03-05T11:02:00Z",
  },
];
